### ISSUE TITLE
An empty Map sent to a Remote method throws MissingMethodException

### ISSUE THREAD

**Issue by reneederer** [dotnet-websharper/websharper#869]
``` F#
namespace MyApp
open WebSharper
open WebSharper.UI.Next
open WebSharper.UI.Next.Client
open WebSharper.UI.Next.Html

module Types =
    [<JavaScript>]
    type Document =
        { map : Map<string, string>
        }

module Server =
    open Types
    [<Remote>]
    let getDocument () =
        async {
            return { map = Map.empty }
        }

    [<Remote>]
    let doNothing (document : Document) =
        async {
            return ()
        }

module Client =
    open Types
    [<JavaScript>]
    let home () = 
        let documentAction () =
            async {
                let! document = Server.getDocument()
                // The next line throws MissingMethodException, no parameterless constructor defined
                do! Server.doNothing document
            }

        div
          [ buttonAttr [on.click (fun _ _ -> documentAction () |> Async.Start)] [text "Action"] ]
```

Error message:

> System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at WebSharper.Core.Json.recordDecoder@1052.Invoke(Value x)
   at WebSharper.Core.Remoting.getParameterDecoder@130-3.Invoke(Value x)
   at WebSharper.Core.Remoting.toConverter@153.Invoke(Value j)
   at WebSharper.Core.Remoting.Server.HandleRequest(Request req)
   at WebSharper.Web.RemotingExtensions.Server.HandleRequest(Server this, Request req, Context context)
   at <StartupCode$WebSharper-Owin>.$Owin.Sitelets.Invoke@525-5.Invoke(String _arg2)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.args@823-1.Invoke(a a)

WebSharper version: 4.0.1.171
Target Framework: 4.6.1
F# Runtime: 4.4.1.0

**Comment by granicz** [comment]
A quick workaround is using a list (of tuples) instead of the map, and converting that to a map on the client.

**Comment by Jand42** [comment]
@reneederer Thanks for the report! On further testing, this happens only on an empty Map (and not with an empty Set), but is indeed a bug.
